apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::440554138148:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BLKNQLVCCDGZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::440554138148:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-03T23:37:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1453"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 60617c33-b146-413b-bebb-c138c6e30591
