apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::440554138148:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build  \n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn:arn:aws:iam::440554138148:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-TF7E7OYXA0Q2\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-02T18:49:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "52509"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5f51ff60-cc64-4f1a-beaf-efb57975e7b4
