<<<<<<< HEAD
# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

=======
>>>>>>> thomas
apiVersion: v1
data:
  mapRoles: |
    - groups:
<<<<<<< HEAD
      - system:masters
      rolearn: arn:aws:iam::644752792305:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::644752792305:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17C402QC9VF6L
      username: system:node:{{EC2PrivateDNSName}}
=======
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::440554138148:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BLKNQLVCCDGZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::440554138148:role/UdacityFlaskDeployCBKubectlRole
      username: build
>>>>>>> thomas
  mapUsers: |
    []
kind: ConfigMap
metadata:
<<<<<<< HEAD
  creationTimestamp: "2021-02-26T07:40:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5992"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5bf363cb-504c-4289-93ce-74257aff0de4
=======
  creationTimestamp: "2021-05-03T23:37:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1453"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 60617c33-b146-413b-bebb-c138c6e30591
>>>>>>> thomas
